/**
 * 
 */
package com.service.config;


/**
 * @author raunak
 *
 */
public class KerberosURLConfig {
	
	private final String KERBEROS_APP_AUTHENTICATION_URL;					//Kerberos Server KDC URL 
	private final String KERBEROS_APP_SERVICE_TICKET_REQUEST_URL;		//Keberos Server TGT URL
	private final String KERBEROS_KEY_SERVER_KEY_REQUEST_URL;
	private final String LOGIN_SERVER_APP_AUTHENTICATION_URL;
	private final String LOGIN_SERVER_USER_AUTHENTICATION_URL;
	private final String LOGIN_SERVER_RETRIEVE_USER_INFO_URL;
	
	/**
	 * @param kERBEROS_APP_AUTHENTICATION_URL
	 * @param kERBEROS_APP_SERVICE_TICKET_REQUEST_URL
	 * @param kERBEROS_KEY_SERVER_KEY_REQUEST_URL
	 * @param lOGIN_SERVER_APP_AUTHENTICATION_URL
	 * @param lOGIN_SERVER_USER_AUTHENTICATION_URL
	 */
	public KerberosURLConfig(String kERBEROS_APP_AUTHENTICATION_URL,
			String kERBEROS_APP_SERVICE_TICKET_REQUEST_URL,
			String kERBEROS_KEY_SERVER_KEY_REQUEST_URL,
			String lOGIN_SERVER_APP_AUTHENTICATION_URL,
			String lOGIN_SERVER_USER_AUTHENTICATION_URL, 
			String lOGIN_SERVER_RETRIEVE_USER_INFO_URL) {
		super();
		KERBEROS_APP_AUTHENTICATION_URL = kERBEROS_APP_AUTHENTICATION_URL;
		KERBEROS_APP_SERVICE_TICKET_REQUEST_URL = kERBEROS_APP_SERVICE_TICKET_REQUEST_URL;
		KERBEROS_KEY_SERVER_KEY_REQUEST_URL = kERBEROS_KEY_SERVER_KEY_REQUEST_URL;
		LOGIN_SERVER_APP_AUTHENTICATION_URL = lOGIN_SERVER_APP_AUTHENTICATION_URL;
		LOGIN_SERVER_USER_AUTHENTICATION_URL = lOGIN_SERVER_USER_AUTHENTICATION_URL;
		LOGIN_SERVER_RETRIEVE_USER_INFO_URL = lOGIN_SERVER_RETRIEVE_USER_INFO_URL;
	}


	/**
	 * @return the kERBEROS_APP_AUTHENTICATION_URL
	 */
	public String getKERBEROS_APP_AUTHENTICATION_URL() {
		return KERBEROS_APP_AUTHENTICATION_URL;
	}


	/**
	 * @return the kERBEROS_APP_SERVICE_TICKET_REQUEST_URL
	 */
	public String getKERBEROS_APP_SERVICE_TICKET_REQUEST_URL() {
		return KERBEROS_APP_SERVICE_TICKET_REQUEST_URL;
	}


	/**
	 * @return the kERBEROS_KEY_SERVER_KEY_REQUEST_URL
	 */
	public String getKERBEROS_KEY_SERVER_KEY_REQUEST_URL() {
		return KERBEROS_KEY_SERVER_KEY_REQUEST_URL;
	}


	/**
	 * @return the kERBEROS_LOGIN_SERVER_APP_AUTHENTICATION_URL
	 */
	public String getLOGIN_SERVER_APP_AUTHENTICATION_URL() {
		return LOGIN_SERVER_APP_AUTHENTICATION_URL;
	}


	/**
	 * @return
	 */
	public String getLOGIN_SERVER_USER_AUTHENTICATION_URL() {
		return LOGIN_SERVER_USER_AUTHENTICATION_URL;
	}

	/**
	 * @return the lOGIN_SERVER_RETRIEVE_USER_INFO_URL
	 */
	public String getLOGIN_SERVER_RETRIEVE_USER_INFO_URL() {
		return LOGIN_SERVER_RETRIEVE_USER_INFO_URL;
	}
	
}
