/**
 * 
 */
package com.device.config;

/**
 * @author raunak
 *
 */
public class KerberosURLConfig {
	
	private final String KERBEROS_APP_AUTHENTICATION_URL;					//Kerberos Server KDC URL 
	private final String KERBEROS_APP_SERVICE_TICKET_REQUEST_URL;		//Keberos Server TGT URL
	private final String LOGIN_SERVICE_APP_AUTHENTICATION_URL;			//Login Service App Authentication URL
	private final String LOGIN_SERVICE_USER_AUTHENTICATION_URL;			//Login Service User Authentication URL
	
	
	/**
	 * @param kERBEROS_APP_AUTHENTICATION_URL
	 * @param kERBEROS_APP_SERVICE_TICKET_REQUEST_URL
	 * @param lOGIN_SERVICE_APP_AUTHENTICATION_URL
	 * @param lOGIN_SERVICE_USER_AUTHENTICATION_URL
	 */
	public KerberosURLConfig(String kERBEROS_APP_AUTHENTICATION_URL,
			String kERBEROS_APP_SERVICE_TICKET_REQUEST_URL,
			String lOGIN_SERVICE_APP_AUTHENTICATION_URL,
			String lOGIN_SERVICE_USER_AUTHENTICATION_URL) {
		super();
		KERBEROS_APP_AUTHENTICATION_URL = kERBEROS_APP_AUTHENTICATION_URL;
		KERBEROS_APP_SERVICE_TICKET_REQUEST_URL = kERBEROS_APP_SERVICE_TICKET_REQUEST_URL;
		LOGIN_SERVICE_APP_AUTHENTICATION_URL = lOGIN_SERVICE_APP_AUTHENTICATION_URL;
		LOGIN_SERVICE_USER_AUTHENTICATION_URL = lOGIN_SERVICE_USER_AUTHENTICATION_URL;
	}


	/**
	 * @return Configured KERBEROS_APP_AUTHENTICATION_URL
	 */
	public String getKERBEROS_APP_AUTHENTICATION_URL() {
		return KERBEROS_APP_AUTHENTICATION_URL;
	}


	/**
	 * @return Configured KERBEROS_APP_SERVICE_TICKET_REQUEST_URL
	 */
	public String getKERBEROS_APP_SERVICE_TICKET_REQUEST_URL() {
		return KERBEROS_APP_SERVICE_TICKET_REQUEST_URL;
	}


	/**
	 * @return Configured LOGIN_SERVICE_APP_AUTHENTICATION_URL
	 */
	public String getLOGIN_SERVICE_APP_AUTHENTICATION_URL() {
		return LOGIN_SERVICE_APP_AUTHENTICATION_URL;
	}


	/**
	 * @return Configured LOGIN_SERVICE_USER_AUTHENTICATION_URL
	 */
	public String getLOGIN_SERVICE_USER_AUTHENTICATION_URL() {
		return LOGIN_SERVICE_USER_AUTHENTICATION_URL;
	}
	
	
}
