package com.service.model.app;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;

import javax.management.InvalidAttributeValueException;

import com.service.model.Session;

public class AppSession extends Session{
	
	private String kerberosServiceSessionID;		//Session ID generated by kerberos for the app
	private String appID;							//App username
	private List<UserSession> userSessions;
	private List<Date> authenticators;
	
	public AppSession() {
		userSessions = new ArrayList<UserSession>();
		authenticators = new LinkedList<>();
	}
	
	/**
	 * @return the appID
	 */
	public String getAppID() {
		return appID;
	}

	/**
	 * @param appID the appID to set
	 */
	public void setAppID(String appID) {
		this.appID = appID;
	}

	/**
	 * @return the userSession
	 */
	public List<UserSession> getUserSession() {
		return userSessions;
	}
	/**
	 * @return the kerberosServiceSessionID
	 */
	public String getKerberosServiceSessionID() {
		return kerberosServiceSessionID;
	}
	/**
	 * @param kerberosServiceSessionID the kerberosServiceSessionID to set
	 */
	public void setKerberosServiceSessionID(String kerberosServiceSessionID) {
		this.kerberosServiceSessionID = kerberosServiceSessionID;
	}

	/**
	 * @return the authenticators
	 */
	public List<Date> getAuthenticators() {
		return authenticators;
	}
	
	/**
	 * @param username
	 * @param userSessionID
	 * @return
	 */
	public UserSession createUserSession(String username, String userSessionID){
		
		UserSession userSession = new UserSession();
		userSession.setUsername(username);
		userSession.setSessionID(userSessionID);
		
		userSessions.add(userSession);
		
		return userSession;
	}
	
	/**
	 * @param username
	 * @return
	 */
	public UserSession findUserSessionByUsername(String username){
		
		for(UserSession session: userSessions){
			if (session.getUsername().equals(username)){
				return session;
			}
		}
		return null;
	}
	
	/**
	 * @param sessionID
	 * @return
	 */
	public UserSession findUserSessionBySessionID(String sessionID){
		
		for(UserSession session: userSessions){
			if (session.getSessionID().equals(sessionID)){
				return session;
			}
		}
		return null;
	}
	
	
	/**
	 * @param authenticator
	 * @throws InvalidAttributeValueException
	 */
	public void addAuthenticator(Date authenticator) {
		
		if(authenticator == null){
			return;
		}
		authenticators.add(authenticator);
	}
	
	/**
	 * @param authenticator
	 * @return
	 * @throws InvalidAttributeValueException
	 */
	public boolean validateAuthenticator(Date authenticator) {
		
		if(authenticator == null){
			return false;
		}
		
		Date lastAuthenticator;
		if (authenticators.size() > 0)
			lastAuthenticator = authenticators.get(authenticators.size()-1);
		else
			return true;
		
		if (authenticator.getTime() - lastAuthenticator.getTime() != 60000) {
			return false;
		}
		return true;
	}
}
