/**
 * 
 */
package com.device.kerberos.model;

import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * This class manages the <strong>Kerberos App Session</strong>
 * 
 * @author raunak
 *
 */
@Component
@Scope(value=ConfigurableBeanFactory.SCOPE_SINGLETON)
public class KerberosSessionManager {

	private KerberosAppSession kerberosAppSession;

	/**
	 * @return the appSession
	 */
	public KerberosAppSession getKerberosAppSession() {
		return kerberosAppSession;
	}

	/**
	 * Creates a Kerberos APP Session
	 * @param <code>String</code> Session ID generated by kerberos Server for App
	 * @param <code>String</code> KDC Master Key Encrypted TGT Packet returned by the Kerberos Server  
	 * @return <code>KerberosAppSession</code> or null if the input is invalid
	 */
	public KerberosAppSession createKerberosAppSession(String sessionID, String TGTPacket) {
		
		if (sessionID == null || sessionID.isEmpty() || TGTPacket == null || TGTPacket.isEmpty()){
			return null;
		}
		
		kerberosAppSession = new KerberosAppSession();
		kerberosAppSession.setSessionID(sessionID);
		kerberosAppSession.setTgt(new TGT(TGTPacket));
		
		return kerberosAppSession;
	}	
}