/**
 * 
 */
package com.device.kerberos.model;

import org.springframework.stereotype.Component;

/**
 * @author raunak
 *
 */
@Component
public class KerberosSessionManager {

	private KerberosAppSession appSession;

	/**
	 * @return the appSession
	 */
	public KerberosAppSession getAppSession() {
		return appSession;
	}

	/**
	 * Creates a Kerberos APP Session
	 * @param sessionID: Session ID generated by kerberos Server for App
	 * @param TGTPacket: Encrypted TGT Packet encrypted by KDC Master Key
	 * @return created KerberosAppSession or null if the input is invalid
	 */
	public KerberosAppSession createKerberosAppSession(String sessionID, String TGTPacket) {
		
		if (sessionID == null || sessionID.isEmpty() || TGTPacket == null || TGTPacket.isEmpty()){
			return null;
		}
		
		appSession = new KerberosAppSession();
		appSession.setSessionID(sessionID);
		appSession.setTgt(new TGT(TGTPacket));
		
		return appSession;
	}	
}