/**
 * 
 */
package com.device.kerberos.model;

import org.springframework.stereotype.Component;

/**
 * @author raunak
 *
 */
@Component
public class KerberosSessionManager {

	private KerberosAppSession kerberosAppSession;

	/**
	 * @return the appSession
	 */
	public KerberosAppSession getKerberosAppSession() {
		return kerberosAppSession;
	}

	/**
	 * Creates a Kerberos APP Session
	 * @param sessionID: Session ID generated by kerberos Server for App
	 * @param TGTPacket: Encrypted TGT Packet encrypted by KDC Master Key
	 * @return created KerberosAppSession or null if the input is invalid
	 */
	public KerberosAppSession createKerberosAppSession(String sessionID, String TGTPacket) {
		
		if (sessionID == null || sessionID.isEmpty() || TGTPacket == null || TGTPacket.isEmpty()){
			return null;
		}
		
		kerberosAppSession = new KerberosAppSession();
		kerberosAppSession.setSessionID(sessionID);
		kerberosAppSession.setTgt(new TGT(TGTPacket));
		
		return kerberosAppSession;
	}	
}